### ISSUE TITLE
Support full markdown

### ISSUE THREAD

**Issue by akshaybhalotia** [hasgeek/hasmail#20]
Right now, some headings (h1 and h2, when last tested) and tables are not supported in the editor

**Comment by booleanbalaji** [comment]
Option to upload a .txt, .rtf or .md file to sendmail would be nice too. I prefer to use a native markdown app on my computer.

**Comment by jace** [comment]
@booleanbalaji Copy paste?

**Comment by jace** [comment]
Open your .md file in a text editor and copy paste from there for now. I'm deferring all work on Hasmail until the new website is live.

**Comment by jace** [comment]
We replaced Markdown processors a while ago, so this should be resolved.
